### PR TITLE
Fixes #7, another dormant bug

### LINKED ISSUE #7: Basename feature in  #3722 doesn't work after "yarn build"
**Describe the bug**
The feature in  #3722 breaks the "NavLink" with "newTab". The package's homepage (aka basename) doesn't work after "yarn build". 

This works on v3.15.0 tag, shall we revert ?

@haricane8133

**Details**
Conductor UI on the latest main.

**To Reproduce**
1. Build and run the conductor UI
2. Goto Workflow Definitions
3. Click the "Executions" 's Query Link,
4. It doesn't work.

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by haricane8133**
Pull Request type
----
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes (Please run `./gradlew generateLock saveLock` to refresh dependencies)
- [ ] WHOSUSING.md
- [ ] Other (please describe):

**NOTE**: Please remember to run `./gradlew spotlessApply` to fix any format violations.

Changes in this PR
----

_Describe the new behavior from this PR, and why it's needed_
Issue #7 

Alternatives considered
----

_Describe alternative implementation you have considered_

### CODE REVIEW

File: ui/src/components/NavLink.jsx [hunk 1]
```diff
@@ -26,7 +26,8 @@ export default React.forwardRef((props, ref) => {
       </Link>
     );
   } else {
-    const href = absolutePath ? url.toString() : cleanDuplicateSlash(getBasename() + url.toString());
+    // Note: + '/' + is required here
+    const href = absolutePath ? url.toString() : cleanDuplicateSlash(getBasename() + '/' + url.toString());
```
Comment (nhandt2021) [inline ui/src/components/NavLink.jsx:30]: You add 1 more slash then replace it. Does it make sense?

File: ui/src/plugins/fetch.js [hunk 2]
```diff
@@ -41,6 +41,12 @@ export function fetchWithContext(
...
 
+/**
+ * @param {string} path 
+ * @returns path with '/' not duplicated except at ://
+ * 
+ * Note: we need the second .replace() because the first one doesn't catch multiple slashes at the start of the string
+ */
 export function cleanDuplicateSlash(path) {
-  return path.replace(/([^:]\/)\/+/g, "$1");
+  return path.replace(/([^:]\/)\/+/g, "$1").replace(/^(\/)+/, '/');
```
Comment (nhandt2021) [inline ui/src/plugins/fetch.js:51]: Why do we need to replace twice?
I think we should find another regex for this.

File: ui/src/components/NavLink.jsx (hunk 1 above)
Comment (haricane8133) [reply ui/src/components/NavLink.jsx:30]: `getBaseName()` can return either 

`/abc/def`, or `/abc/def/`

We would have to cover both scenarios

Comment (haricane8133) [reply ui/src/components/NavLink.jsx:30]: Those two options are possible because we leave the work of filling the `homepage` field, to the user.

The user can enter the homepage url with a trailing slash, or not... It's up to them, and we should make sure things work both way

File: ui/src/plugins/fetch.js (hunk 2 above)
Comment (haricane8133) [reply ui/src/plugins/fetch.js:51]: The second replace isn't a costly operation as the associated regex has `^`.

Having two regex also ensures the code is more readable with simpler regexes...

Comment (nhandt2021) [reply ui/src/plugins/fetch.js:51]: @haricane8133 Happy new year!
Sorry for late replying.
Here is the regex that I found: `/(https?:\/\/)|(\/)+/g`
Ex: `path.replace(/(https?:\/\/)|(\/)+/g, "$1$2")`

image

Comment (haricane8133) [reply ui/src/plugins/fetch.js:51]: @nhandt2021, this is clever.

But it currently fails for
`'https:///some-domain.com//sub-domain/'.replace(/(https?:\/\/)|(\/)+/g, "$1$2")`

Comment (haricane8133) [reply ui/src/plugins/fetch.js:51]: I would just add a `\/*` after `(https?:\/\/)` to fix it

`'https:///some-domain.com//sub-domain/'.replace(/(https?:\/\/)\/*|(\/)+/g, "$1$2")`

Do you think it would be better not to pin the protocol? The Util may be used else-where too...

How about this? We can remove `https?` from the regex
`'https:///some-domain.com//sub-domain/'.replace(/(:\/\/)\/*|(\/)+/g, "$1$2")`

Comment (haricane8133) [reply ui/src/plugins/fetch.js]: I have pushed the code with the latest regex, and rebased commits from upstream.

Comment (nhandt2021) [reply ui/src/plugins/fetch.js]: Actually I don't think we need to cover this case because it's completely wrong syntax.
How about if user input a URL like this: `https:#$@@#$@*&#@////////some-domain.abc`

Comment (haricane8133) [reply ui/src/plugins/fetch.js]: We aren't solving for 100% of the possibilities...
(we have a `+ '/'` in our code base elsewhere and we cannot be sure where that extra '/' would be appended)

But we **MUST** make sure that the function, which deals only with '/', does what is expected out of it.

Comment (nhandt2021) [reply ui/src/plugins/fetch.js]: > Do you think it would be better not to pin the protocol? The Util can be used elsewhere too... (the existing code didn't specify the protocol)
> 
> How about this? We can remove `https?` from the regex `'https:///some-domain.com//sub-domain/'.replace(/(:\/\/)\/*|(\/)+/g, "$1$2")`
> 
> Let us have the function as generic as possible

Agree with this :)

**Review by nhandt2021 — APPROVED** [review]
Looks good to me.

**Review by v1r3n — APPROVED** [review]
